version: '3.4'

services:
  authorization:
    image: ${DOCKER_REGISTRY-}authorizationapi
    build:
      context: .
      dockerfile: Authorization/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"