# version: '3.4'
services:
  authorization:
    image: ${DOCKER_REGISTRY-}authorizationapi
    build:
      context: .
      dockerfile: Authorization/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Database=auth_db;Username=postgres;Password=${DB_PASSWORD}
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

  db:
    image: postgres:latest
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"